### ISSUE TITLE
'Griptape Display : Data as Text' does not work

### ISSUE THREAD

**Issue by Hullabalo** [griptape-ai/ComfyUI-Griptape#108]
Hi, and thanks for your work on this suite of nodes!

Maybe it’s just an issue with my setup (latest version of Comfy via Stability Matrix, Win10), but I’ve noticed that the Griptape node 'Display Data as Text' returns an error (tested only with the Ollama agent) regardless of the desired output data type. It seems that the wildcard "*" on the input is partly to blame.

Locally, I partially resolved the issue by modifying the node's code and adding the following class method, as indicated in the documentation (https://docs.comfy.org/essentials/custom_node_more_on_inputs#wildcard-inputs):

```
@classmethod
def VALIDATE_INPUTS(cls, input_types):
    return True
```
This solved the issue for JSON types CONFIG and MEMORY, but not for others types. I assume (wrongly ?) that Comfy's code has secured the STRING type, and it may no longer be possible to pass complex types by casting them with str(INPUT) ? But I haven't had time to investigate further. Maybe someone smarter than me got the answer ? ;)

**Comment by shhlife** [comment]
Thank you for the node - I'll check it out! I know that ComfyUI has been updated quite a bit lately & I figured that would have an impact on the nodes. I'll update and check it out.

**Comment by Hullabalo** [comment]
Great, thanks! I'm also looking into it on my end. I think I'll encounter the same issue with my own custom nodes when I test them on the new release. Have a nice day!

**Comment by shhlife** [comment]
I added the fix you recommended & also updated my code to display data in the node so it can handle just plain strings.. do you have an example I could try where it wasn't working correctly?

**Comment by shhlife** [comment]
Please check it out and let me know if it works for you :)

**Comment by Hullabalo** [comment]
Hello Jason! Sorry, I'm a bit late. I've just completed the update, and I can confirm that the DataAsText node is now working perfectly. As for the workflow, I would be hard-pressed to provide a use case right away, as I am still in the discovery phase regarding Griptape. However, I am already starting to find some uses. 
In the near future, I plan to use it to generate graphic files in vector format to assist my own nodes. It may not sound very exciting to others ... but for me, oh hell it already is! ;)

Once again, a big thank you.

**Comment by shhlife** [comment]
@Hullabalo glad to hear it works for you! :)

would love to see how it works out for the graphic files in vector format - keep us informed with how it's going! :)

cheers,
Jason

**Comment by Hullabalo** [comment]
Haha, I think I'm going to have to work hard to make LLaMA 3 understand that a five-pointed star definitely needs to have five points, not four. But I guess I should learn to write understandable rulesets first before I can teach anything to an LLM.

Of course, I'll be sure to share my progress here and elsewhere, you can count on that ! Speaking of elsewhere, I'm surprised there's not more hype around ComfyUI-Griptape here: https://www.reddit.com/r/comfyui/search/?q=griptape. It would be well-deserved !
All the best.

**Comment by shhlife** [comment]
It'd be awesome if you wanted to add to that hype a bit more.. always feels
better coming from the community. :)
