### ISSUE TITLE
Ollama not working?

### ISSUE THREAD

**Issue by Excidos** [griptape-ai/ComfyUI-Griptape#114]
Hi whenever I try do anything with the Griptape framework in ComfyUI I keep getting OpenAI related errors even though I'm trying to use Ollama

Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-U1U8F***************************************PSlb. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}

Ollama with Griptape worked in the past until I tried to use it recently.

**Comment by shhlife** [comment]
Hi @Excidos it should be working - I use Ollama all the time. It does look like it's trying to use an API key for an OpenAI node..

Can you try removing and re-installing your griptape nodes? It may be that you have an older copy of the nodes.

If that doesn't work, can you show me you workflow? maybe you have an OpenAI node in there that doesn't have a proper key?

**Comment by shhlife** [comment]
I have verified that this will work w/out the need for an OPENAI_API_KEY in the upcoming release
![image](https://github.com/user-attachments/assets/4ceb304f-2cde-47ec-b72c-ad948eba5f18)
