### ISSUE TITLE
Agents not using tools

### ISSUE THREAD

**Issue by beanhilton** [griptape-ai/ComfyUI-Griptape#115]
Hi stumbled on this project yesterday and it looks great. 
However, while I have some 'working' workflows in comfyui using LMStudio I feel like tools and agents as tools are being ignored. 

Even the simplest workflow asking for the day of the week with DateTime tool the LLM is just making something up or is saying it doesn't know.

I see in logs for example :
"role": "assistant "
"content":"Action 1: Get Current Date etc ... \n\nAction Output: 2023-02-20\n\n Action 2: Extract Day of the Week... 

Is this normal?

**Comment by shhlife** [comment]
Hi, thanks for checking out the project! I have also noticed issues with lmstudio and its ability to handle tools. I was able to get ollama to work running the same models, would you be able to give that a try?

**Comment by beanhilton** [comment]
Wow quick response... ok I'll give it a go.

**Comment by shhlife** [comment]
Hah! Yeah, I woke up early with a bad cold and couldn't sleep. :)definitely let me know how it goes - llama3.1 should be able to handle tools usage!

**Comment by beanhilton** [comment]
i was using llama3.1 in LMStudio ...

Ollama is now set up (on windows) and I have the date and time 👍 

Thanks.

**Comment by shhlife** [comment]
Awesome! I’m glad that’s working :) I’ll keep an eye on lmstudio and see if there is anything we can do to enable tools to work properly.
