### ISSUE TITLE
Ollama error with Griptape run: Agent

### ISSUE THREAD

**Issue by FemBoxbrawl** [griptape-ai/ComfyUI-Griptape#116]
![Screenshot 2024-09-02 093916](https://github.com/user-attachments/assets/e3aba17e-fcf7-4c67-a9fd-2d5c784ebe74)
![Screenshot 2024-09-02 094009](https://github.com/user-attachments/assets/879b5835-b19c-49f6-87ad-78405de9e3f9)

the disable workflow works, but not the other one.

**Comment by FemBoxbrawl** [comment]
"The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable"

**Comment by FemBoxbrawl** [comment]
I needed to put in an Openai api key and then it works

**Comment by shhlife** [comment]
The non-disabled workflow should still be working - you don't have any nodes that require openai api keys.

When did you last install the griptape nodes?

**Comment by FemBoxbrawl** [comment]
I reinstalled freshly

I entered an API key, but then the Ollama worked with the create agent node

**Comment by shhlife** [comment]
I've verified this will work in the upcoming release w/out an effective OPENAI_API_KEY. :)

![image](https://github.com/user-attachments/assets/82fd37e7-ddde-4c56-bb97-58883e118a5c)

**Comment by shhlife** [comment]
closing - please let me know if this is still an issue
