### ISSUE TITLE
How do I create a local RAG worflow? (with ollama embedding model?)

### ISSUE THREAD

**Issue by FemBoxbrawl** [griptape-ai/ComfyUI-Griptape#117]
Is the an example workflow where I can load files  in comfyui and then use an ollama embedding model to do rag with an LLM (ollama)

**Comment by auxon** [comment]
It's coming ... https://www.loom.com/share/34768ceb54d94f789ab57cee57e8460e?sid=3803d380-9ac1-4066-a173-cf370907e108

**Comment by shhlife** [comment]
To! I'm working on a pretty major refactor of the configs this week, and then will release both that and the configs at the same time.

Also got a lot of customer meetings this week so my time will be a bit tight :)

**Comment by shhlife** [comment]
It's available now - in the examples folder:

https://github.com/griptape-ai/ComfyUI-Griptape/blob/main/examples/retrieval_augmented_generation.png

**Comment by FemBoxbrawl** [comment]
thank you so much! will be super helpful!
