### ISSUE TITLE
Issue: (IMPORT FAILED): D:\Stable_Diffusion\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\ComfyUI-Griptape

### ISSUE THREAD

**Issue by RamonGuthrie** [griptape-ai/ComfyUI-Griptape#127]
File "D:\Stable_Diffusion\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\ComfyUI-Griptape\__init__.py", line 14, in <module>
    from .nodes.agent.CreateAgent import CreateAgent
  File "D:\Stable_Diffusion\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\ComfyUI-Griptape\nodes\agent\CreateAgent.py", line 1, in <module>
    from .BaseAgent import BaseAgent
  File "D:\Stable_Diffusion\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\ComfyUI-Griptape\nodes\agent\BaseAgent.py", line 1, in <module>
    from griptape.drivers import DummyVectorStoreDriver
ModuleNotFoundError: No module named 'griptape'

Cannot import D:\Stable_Diffusion\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\ComfyUI-Griptape module for custom nodes: No module named 'griptape'

**Comment by shhlife** [comment]
Thank you for your error - are you seeing this when you launch comfyUI or when you try and install Griptape?

**Comment by RamonGuthrie** [comment]
ComfyUI-Griptape just won't install!

**Comment by shhlife** [comment]
Thanks @RamonGuthrie - I see you're on windows, are you trying to install via the ComfyUI Manager, or manually?

**Comment by shhlife** [comment]
Thank you @mister-wise - how did you install ComfyUI? Are you using it from GitHub, or are you running another way?

**Comment by mister-wise** [comment]
@shhlife  I downloaded ComfyUI_windows_portable_nvidia.7z from releases from Github.

**Comment by shhlife** [comment]
It sounds like there's a torch issue.. re-installing torch (it's called out in the README, but I could probably make that more visible :) ) seems to work well. Can you give it a try?

https://github.com/griptape-ai/ComfyUI-Griptape?tab=readme-ov-file#torch-issues

**Comment by mister-wise** [comment]
Hmm well I re-install torch but still got:
`[ComfyUI-Easy-Use] web root: E:\Projekty\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use\web_version/v2 Loaded
Traceback (most recent call last):
  File "E:\Projekty\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\Projekty\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Griptape\__init__.py", line 14, in <module>
    from .nodes.agent.CreateAgent import CreateAgent
  File "E:\Projekty\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Griptape\nodes\agent\CreateAgent.py", line 1, in <module>
    from .BaseAgent import BaseAgent
  File "E:\Projekty\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Griptape\nodes\agent\BaseAgent.py", line 1, in <module>
    from griptape.drivers import DummyVectorStoreDriver
ModuleNotFoundError: No module named 'griptape'` 


this is me current `pip freeze`

absl-py==2.1.0
accelerate==0.34.2
addict==2.4.0
aiohappyeyeballs @ file:///D:/a/ComfyUI/cu124_python_deps/aiohappyeyeballs-2.4.0-py3-none-any.whl#sha256=7ce92076e249169a13c2f49320d1967425eaf1f407522d707d59cac7628d62bd
aiohttp @ file:///D:/a/ComfyUI/cu124_python_deps/aiohttp-3.10.5-cp311-cp311-win_amd64.whl#sha256=349ef8a73a7c5665cca65c88ab24abe75447e28aa3bc4c93ea5093474dfdf0ff
aiosignal @ file:///D:/a/ComfyUI/cu124_python_deps/aiosignal-1.3.1-py3-none-any.whl#sha256=f8376fb07dd1e86a584e4fcdec80b36b7f81aac666ebc724e2c090300dd83b17
albucore==0.0.17
albumentations==1.4.16
annotated-types==0.7.0
antlr4-python3-runtime==4.9.3
anyio==4.4.0
argostranslate==1.9.6
attrs @ file:///D:/a/ComfyUI/cu124_python_deps/attrs-24.2.0-py3-none-any.whl#sha256=81921eb96de3191c8258c199618104dd27ac608d9366f5e35d011eae1867ede2
beautifulsoup4==4.12.3
bitsandbytes==0.44.1
boto3==1.35.29
botocore==1.35.29
certifi @ file:///D:/a/ComfyUI/cu124_python_deps/certifi-2024.8.30-py3-none-any.whl#sha256=922820b53db7a7257ffbda3f597266d435245903d80737e34f8a45ff3e3230d8
cffi @ file:///D:/a/ComfyUI/cu124_python_deps/cffi-1.17.1-cp311-cp311-win_amd64.whl#sha256=caaf0640ef5f5517f49bc275eca1406b0ffa6aa184892812030f04c2abf589a0
chardet==5.2.0
charset-normalizer @ file:///D:/a/ComfyUI/cu124_python_deps/charset_normalizer-3.3.2-cp311-cp311-win_amd64.whl#sha256=663946639d296df6a2bb2aa51b60a2454ca1cb29835324c640dafb5ff2131a77
click==8.1.7
clip-interrogator==0.6.0
cmake==3.30.3
color-matcher==0.5.0
colorama @ file:///D:/a/ComfyUI/cu124_python_deps/colorama-0.4.6-py2.py3-none-any.whl#sha256=4f1d9991f5acc0ca119f9d443620b77f9d6b33703e51011c16baf57afb285fc6
coloredlogs==15.0.1
colorlog==6.8.2
contourpy==1.3.0
cryptography==43.0.1
cssselect2==0.7.0
cstr @ git+https://github.com/WASasquatch/cstr@0520c29a18a7a869a6e5983861d6f7a4c86f8e9b
ctranslate2==4.4.0
cycler==0.12.1
ddt==1.7.2
deep-translator==1.11.4
Deprecated==1.2.14
diffusers==0.30.3
dill==0.3.9
distro==1.9.0
docutils==0.21.2
einops @ file:///D:/a/ComfyUI/cu124_python_deps/einops-0.8.0-py3-none-any.whl#sha256=9572fb63046264a862693b0a87088af3bdc8c068fde03de63453cbbde245465f
eval_type_backport==0.2.0
fairscale==0.4.13
ffmpy @ git+https://github.com/WASasquatch/ffmpy.git@f000737698b387ffaeab7cd871b0e9185811230d
filelock @ file:///D:/a/ComfyUI/cu124_python_deps/filelock-3.15.4-py3-none-any.whl#sha256=6ca1fffae96225dab4c6eaf1c4f4f28cd2568d3ec2a44e15a08520504de468e7
flatbuffers==24.3.25
fonttools==4.53.1
frozenlist @ file:///D:/a/ComfyUI/cu124_python_deps/frozenlist-1.4.1-cp311-cp311-win_amd64.whl#sha256=fb3c2db03683b5767dedb5769b8a40ebb47d6f7f45b1b3e3b4b51ec8ad9d9825
fsspec @ file:///D:/a/ComfyUI/cu124_python_deps/fsspec-2024.9.0-py3-none-any.whl#sha256=a0947d552d8a6efa72cc2c730b12c41d043509156966cca4fb157b0f2a0c574b
ftfy==6.2.3
fvcore==0.1.5.post20221221
gitdb==4.0.11
GitPython==3.1.43
googletrans-py==4.0.0
h11==0.14.0
h2==4.1.0
hpack==4.0.0
httpcore==1.0.5
httpx==0.27.2
huggingface-hub @ file:///D:/a/ComfyUI/cu124_python_deps/huggingface_hub-0.24.6-py3-none-any.whl#sha256=a990f3232aa985fe749bc9474060cbad75e8b2f115f6665a9fda5b9c97818970
humanfriendly==10.0
hydra-core==1.3.2
hyperframe==6.0.1
idna @ file:///D:/a/ComfyUI/cu124_python_deps/idna-3.8-py3-none-any.whl#sha256=050b4e5baadcd44d760cedbd2b8e639f2ff89bbc7a5730fcc662954303377aac
imageio==2.35.1
imageio-ffmpeg==0.5.1
img2texture @ git+https://github.com/WASasquatch/img2texture.git@d6159abea44a0b2cf77454d3d46962c8b21eb9d3
importlib_metadata==8.5.0
iopath==0.1.10
jax==0.4.33
jaxlib==0.4.33
Jinja2 @ file:///D:/a/ComfyUI/cu124_python_deps/jinja2-3.1.4-py3-none-any.whl#sha256=bc5dd2abb727a5319567b7a813e6a2e7318c39f4f487cfe6c89c6f9c7d25197d
jiter==0.5.0
jmespath==1.0.1
joblib==1.4.2
json_repair==0.29.7
jsonschema==4.23.0
jsonschema-specifications==2023.12.1
kiwisolver==1.4.7
kornia @ file:///D:/a/ComfyUI/cu124_python_deps/kornia-0.7.3-py2.py3-none-any.whl#sha256=f2175f7244a220443111917f8ccaf0242ac9c20401b9824b5c0dacddb37f3258
kornia_rs @ file:///D:/a/ComfyUI/cu124_python_deps/kornia_rs-0.1.5-cp311-none-win_amd64.whl#sha256=9491d260bbdd43fad55e9bf15ade851be8b0fed4a341b9db40b1a8a43fab483b
lark-parser==0.12.0
lazy_loader==0.4
lightning-utilities==0.11.7
llvmlite==0.43.0
loralib==0.1.2
lxml==5.3.0
manifold3d==2.5.1
mapbox_earcut==1.0.2
markdown-it-py==3.0.0
MarkupSafe @ file:///D:/a/ComfyUI/cu124_python_deps/MarkupSafe-2.1.5-cp311-cp311-win_amd64.whl#sha256=2b7c57a4dfc4f16f7142221afe5ba4e093e09e728ca65c51f5620c9aaeb9a617
matplotlib==3.9.2
matrix-client==0.4.0
mdurl==0.1.2
mediapipe==0.10.14
ml_dtypes==0.5.0
mpmath @ file:///D:/a/ComfyUI/cu124_python_deps/mpmath-1.3.0-py3-none-any.whl#sha256=a0b2b9fe80bbcd81a6647ff13108738cfb482d481d826cc0e02f5b35e5c88d2c
mss==9.0.2
multidict @ file:///D:/a/ComfyUI/cu124_python_deps/multidict-6.0.5-cp311-cp311-win_amd64.whl#sha256=2faa5ae9376faba05f630d7e5e6be05be22913782b927b19d12b8145968a85ea
natsort==8.4.0
networkx @ file:///D:/a/ComfyUI/cu124_python_deps/networkx-3.3-py3-none-any.whl#sha256=28575580c6ebdaf4505b22c6256a2b9de86b316dc63ba9e93abde3d78dfdbcf2
numba==0.60.0
numpy @ file:///D:/a/ComfyUI/cu124_python_deps/numpy-1.26.4-cp311-cp311-win_amd64.whl#sha256=cd25bcecc4974d09257ffcd1f098ee778f7834c3ad767fe5db785be9a4aa9cb2
omegaconf==2.3.0
onnx==1.16.2
onnxruntime==1.19.2
onnxruntime-gpu==1.18.0
open_clip_torch==2.26.1
openai==1.50.2
opencv-contrib-python==4.10.0.84
opencv-python==4.10.0.84
opencv-python-headless==4.10.0.84
opt_einsum==3.4.0
packaging @ file:///D:/a/ComfyUI/cu124_python_deps/packaging-24.1-py3-none-any.whl#sha256=5b8f2217dbdbd2f7f384c41c628544e6d52f2d0f53c6d0c3ea61aa5d1d7ff124
pandas==2.2.3
piexif==1.1.3
pilgram==1.2.1
pillow @ file:///D:/a/ComfyUI/cu124_python_deps/pillow-10.4.0-cp311-cp311-win_amd64.whl#sha256=cbed61494057c0f83b83eb3a310f0bf774b09513307c434d4366ed64f4128a91
platformdirs==4.3.3
pooch==1.8.2
portalocker==2.10.1
protobuf==4.25.5
psutil @ file:///D:/a/ComfyUI/cu124_python_deps/psutil-6.0.0-cp37-abi3-win_amd64.whl#sha256=33ea5e1c975250a720b3a6609c490db40dae5d83a4eb315170c4fe0d8b1f34b3
py-cpuinfo==9.0.0
pycocoevalcap==1.2
pycocotools==2.0.8
pycollada==0.8
pycparser @ file:///D:/a/ComfyUI/cu124_python_deps/pycparser-2.22-py3-none-any.whl#sha256=c3702b6d3dd8c7abc1afa565d7e63d53a1d0bd86cdc24edd75470f4de499cfcc
pydantic==2.9.2
pydantic_core==2.23.4
pygit2 @ file:///D:/a/ComfyUI/cu124_python_deps/pygit2-1.15.1-cp311-cp311-win_amd64.whl#sha256=167c23272b225ddd3be1e794bd8085b3c4e394cbdb70a1be278ab32e228ccedc
PyGithub==2.4.0
Pygments==2.18.0
PyJWT==2.9.0
pykalman==0.9.7
PyMatting==1.1.12
PyNaCl==1.5.0
pyOpenSSL==24.2.1
pyparsing==3.1.4
pypng==0.20220715.0
pyreadline3==3.5.2
python-dateutil==2.9.0.post0
python-dotenv==1.0.1
pytorch-lightning==2.4.0
pytz==2024.2
pywin32==306
PyYAML @ file:///D:/a/ComfyUI/cu124_python_deps/PyYAML-6.0.2-cp311-cp311-win_amd64.whl#sha256=e10ce637b18caea04431ce14fabcf5c64a1c61ec9c56b071a4b7ca131ca52d44
qrcode==7.4.2
referencing==0.35.1
regex @ file:///D:/a/ComfyUI/cu124_python_deps/regex-2024.7.24-cp311-cp311-win_amd64.whl#sha256=538d30cd96ed7d1416d3956f94d54e426a8daf7c14527f6e0d6d425fcb4cca52
rembg==2.0.59
reportlab==4.2.4
requests @ file:///D:/a/ComfyUI/cu124_python_deps/requests-2.32.3-py3-none-any.whl#sha256=70761cfe03c773ceb22aa2f671b4757976145175cdfca038c02654d061d6dcc6
rich==13.8.1
rpds-py==0.20.0
Rtree==1.3.0
s3transfer==0.10.2
sacremoses==0.0.53
safetensors @ file:///D:/a/ComfyUI/cu124_python_deps/safetensors-0.4.5-cp311-none-win_amd64.whl#sha256=cbd39cae1ad3e3ef6f63a6f07296b080c951f24cec60188378e43d3713000c04
scenedetect==0.6.4
scikit-image==0.24.0
scikit-learn==1.5.2
scipy @ file:///D:/a/ComfyUI/cu124_python_deps/scipy-1.14.1-cp311-cp311-win_amd64.whl#sha256=716e389b694c4bb564b4fc0c51bc84d381735e0d39d3f26ec1af2556ec6aad94
seaborn==0.13.2
segment-anything==1.0
sentencepiece @ file:///D:/a/ComfyUI/cu124_python_deps/sentencepiece-0.2.0-cp311-cp311-win_amd64.whl#sha256=0993dbc665f4113017892f1b87c3904a44d0640eda510abcacdfb07f74286d36
shapely==2.0.6
shellingham==1.5.4
simpleeval==0.9.13
six==1.16.0
smmap==5.0.1
sniffio==1.3.1
sounddevice==0.5.0
soundfile @ file:///D:/a/ComfyUI/cu124_python_deps/soundfile-0.12.1-py2.py3-none-win_amd64.whl#sha256=0d86924c00b62552b650ddd28af426e3ff2d4dc2e9047dae5b3d8452e0a49a77
soupsieve==2.6
spandrel @ file:///D:/a/ComfyUI/cu124_python_deps/spandrel-0.3.4-py3-none-any.whl#sha256=1b5585bcb0298fc817e5b556880431353f48770f98328c3ce54f4ed9768f2c13
stanza==1.1.1
svg.path==6.3
svglib==1.5.1
sympy @ file:///D:/a/ComfyUI/cu124_python_deps/sympy-1.13.2-py3-none-any.whl#sha256=c51d75517712f1aed280d4ce58506a4a88d635d6b5dd48b39102a7ae1f3fcfe9
tabulate==0.9.0
termcolor==2.4.0
threadpoolctl==3.5.0
tifffile==2024.8.30
timm==1.0.9
tinycss2==1.3.0
tokenizers @ file:///D:/a/ComfyUI/cu124_python_deps/tokenizers-0.19.1-cp311-none-win_amd64.whl#sha256=ad57d59341710b94a7d9dbea13f5c1e7d76fd8d9bcd944a7a6ab0b0da6e0cc66
tomli==2.0.1
torch==2.4.1+cu121
torchaudio==2.4.1+cu121
torchmetrics==1.4.2
torchsde @ file:///D:/a/ComfyUI/cu124_python_deps/torchsde-0.2.6-py3-none-any.whl#sha256=19bf7ff02eec7e8e46ba1cdb4aa0f9db1c51d492524a16975234b467f7fc463b
torchvision==0.19.1+cu121
tqdm @ file:///D:/a/ComfyUI/cu124_python_deps/tqdm-4.66.5-py3-none-any.whl#sha256=90279a3770753eafc9194a0364852159802111925aa30eb3f9d85b0e805ac7cd
trampoline @ file:///D:/a/ComfyUI/cu124_python_deps/trampoline-0.1.2-py3-none-any.whl#sha256=36cc9a4ff9811843d177fc0e0740efbd7da39eadfe6e50c9e2937cbc06d899d9
transformers @ file:///D:/a/ComfyUI/cu124_python_deps/transformers-4.44.2-py3-none-any.whl#sha256=1c02c65e7bfa5e52a634aff3da52138b583fc6f263c1f28d547dc144ba3d412d
trimesh==4.4.9
typer==0.12.5
typing_extensions @ file:///D:/a/ComfyUI/cu124_python_deps/typing_extensions-4.12.2-py3-none-any.whl#sha256=04e5ca0351e0f3f85c6853954072df659d0d13fac324d0072316b67d7794700d
tzdata==2024.2
ultralytics==8.3.1
ultralytics-thop==2.0.8
urllib3==1.26.20
vhacdx==0.0.8.post1
watchdog==5.0.3
wcwidth==0.2.13
webencodings==0.5.1
wrapt==1.16.0
xatlas==0.0.9
xxhash==3.5.0
yacs==0.1.8
yapf==0.40.2
yarl @ file:///D:/a/ComfyUI/cu124_python_deps/yarl-1.9.11-cp311-cp311-win_amd64.whl#sha256=9fae7ec5c9a4fe22abb995804e6ce87067dfaf7e940272b79328ce37c8f22097
zipp==3.20.2

**Comment by shhlife** [comment]
It's definitely having trouble with installing Griptape.. let's see if this specific install will work:

 ```
 pip install python-dotenv griptape[drivers-prompt-cohere,drivers-prompt-anthropic,drivers-prompt-huggingface-hub,drivers-prompt-amazon-bedrock,drivers-prompt-amazon-sagemaker,drivers-prompt-google,drivers-prompt-ollama,drivers-embedding-amazon-bedrock,drivers-embedding-amazon-sagemaker,drivers-embedding-huggingface,drivers-embedding-voyageai,drivers-embedding-google,drivers-embedding-cohere,drivers-text-to-speech-elevenlabs,drivers-vector-pinecone,drivers-vector-marqo,drivers-vector-mongodb,drivers-vector-redis,drivers-vector-opensearch,drivers-vector-pgvector,drivers-vector-qdrant,drivers-web-scraper-trafilatura,drivers-web-scraper-markdownify,drivers-web-search-duckduckgo,loaders-dataframe,loaders-pdf,loaders-image,loaders-email,loaders-audio]==0.31.0
 ```
 
 can you let me know what errors you get then, if any?

**Comment by mister-wise** [comment]
@shhlife sorry for delay. I tried use this install command, but it failed. After many hours and more logs like this:
`INFO: pip is looking at multiple versions of dnspython to determine which version is compatible with other requirements. This could take a while.
Collecting dnspython<3.0.0,>=1.16.0
  Using cached dnspython-2.6.1-py3-none-any.whl (307 kB)
INFO: pip is looking at multiple versions of distro to determine which version is compatible with other requirements. This could take a while.
Collecting distro<2,>=1.7.0
  Using cached distro-1.8.0-py3-none-any.whl (20 kB)
INFO: pip is looking at multiple versions of courlan to determine which version is compatible with other requirements. This could take a while.
Collecting courlan>=1.2.0
  Downloading courlan-1.3.0-py3-none-any.whl (33 kB)
INFO: pip is looking at multiple versions of click to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of charset-normalizer to determine which version is compatible with other requirements. This could take a while.
Collecting charset-normalizer<4,>=2
  Using cached charset_normalizer-3.3.1-cp310-cp310-win_amd64.whl (98 kB)
INFO: pip is looking at multiple versions of certifi to determine which version is compatible with other requirements. This could take a while.
Collecting certifi>=2024.07.04
  Using cached certifi-2024.7.4-py3-none-any.whl (162 kB)
INFO: pip is looking at multiple versions of botocore to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of async-timeout to determine which version is compatible with other requirements. This could take a while.
`

I got: `pip._vendor.resolvelib.resolvers.ResolutionTooDeep: 200000`

**Comment by shhlife** [comment]
okay, what other addons do you have?

Are you running within a virtual environment where ComfyUI is the only stuff in this venv, or is this the same python environment for everything on your machine?

**Comment by shhlife** [comment]
Okay, cool! If you could temporarily disable them to help us diagnose where the problem is, that'd be great. I'm trying to figure out if it's just Griptape, or a combo of Griptape + another plugin. If we can figure out which two plugins cause the issue, I can resolve it. :)

cheers!

**Comment by shhlife** [comment]
We've just pushed a new release that should resolve this for once and for all. :) please give it a try when you get a chance. :)
