### ISSUE TITLE
Local Ollama and LM Studio models not loading

### ISSUE THREAD

**Issue by freshlesh3** [griptape-ai/ComfyUI-Griptape#138]
![image](https://github.com/user-attachments/assets/1aaf83dd-2700-4205-83e0-be38c09ae045)
I have installed Griptape on my SwarmUI/ComfyUI installation and have OpenAI and Anthropic API keys working fine but the local models don't appear in my list of available models.  I've had similar issues in the past, in standard ComfyUI setups but not sure what is causing it. I have LM studio and Ollama running but they are not recognized by their config nodes.  I've updated the plugin and have the latest version running. Any assistance greatly appreciated. @shhlife

**Comment by shhlife** [comment]
hi @freshlesh3 - what URL are you running LMStudio with? the default should be 127.0.0.1 but might also be `localhost`. if you could check the url and port, that'd be awesome!

**Comment by freshlesh3** [comment]
![image](https://github.com/user-attachments/assets/a1658632-03f4-4280-abe5-f23fcda87a44)
LM Studio uses http://localhost, but even with localhost as the baseurl the model list is still blank which is the main issue.

**Comment by shhlife** [comment]
Okay, can you try executing the following command:

`curl http://localhost:1234/v1/models`

This is what is being run to get a list of the models.. you should see something similar to:

```
{
  "data": [
    {
      "id": "lmstudio-community/Meta-Llama-3.1-8B-Instruct-GGUF/Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf",
      "object": "model",
      "owned_by": "organization-owner",
      "permission": [
        {}
      ]
    }
  ],
  "object": "list"
}

**Comment by freshlesh3** [comment]
I get this:
`{
  "data": [
    {
      "id": "cjpais/llava-1.6-mistral-7b-gguf/llava-v1.6-mistral-7b.Q5_K_S.gguf",
      "object": "model",
      "owned_by": "organization-owner",
      "permission": [
        {}
      ]
    }
  ],
  "object": "list"
}`

**Comment by shhlife** [comment]
okay, cool - are you getting any errors in the ComfyUI console?

**Comment by freshlesh3** [comment]
Ollama error: OllamaEmbeddingDriver.__init__() missing 1 required keyword-only argument: 'model'

LM Studio: Error code: 400 - {'error': '<LM Studio error> . Error Data: n/a, Additional Data: n/a'}

**Comment by shhlife** [comment]
Hmm.. stability matrix.. okay, haven't tried that before, but thank you for letting me know! it sounds like it's having issues for some reason connecting to that url.. if you replace 127.0.0.1 with localhost, does that work?

**Comment by freshlesh3** [comment]
Changing the base_url to http://localhost has no affect in what appears in the model list of either node.

**Comment by shhlife** [comment]
ah! Okay, I think I know the problem.. it's requiring an embedding model. Can you try adding an embedding model to ollama or lmstudio? 

I've been using nomic-embed-text https://ollama.com/library/nomic-embed-text

give that a try?

**Comment by freshlesh3** [comment]
> ah! Okay, I think I know the problem.. it's requiring an embedding model. Can you try adding an embedding model to ollama or lmstudio?
> 
> I've been using nomic-embed-text https://ollama.com/library/nomic-embed-text
> 
> give that a try?

Appreciate the effort. It works fine in the standard ComfyUI setup but Stability Matrix has some issue that does not allow me to listen to an extra websocket endpoint for an unrelated custom node, so I think that might be the issue.

**Comment by shhlife** [comment]
okay - that's something I'll have to look into and see if there's anything special I'll need to do.

In the meantime, LMStudio is actually using the OpenAI Compatible stuff under the hood.. so you could probably switch instead to using the OpenAICompatiblePromptDriver...

This lets you set the model with a text field - just make sure you set the api_key to `lm_studio` and set your url correctly as in the attached image.

![image](https://github.com/user-attachments/assets/1725c9fd-47f4-43a0-8859-bc6d5a3adf62)

**Comment by shhlife** [comment]
Hopefully you're able to continue working with the OpenAiCompatiblePromptDriver. Please re-open this ticket if it's not working!

cheers,
Jason
