### ISSUE TITLE
Installation fails with ComfyUI Manager AND with git clone

### ISSUE THREAD

**Issue by poldos** [griptape-ai/ComfyUI-Griptape#152]
I have tried both ways to install this set of custom nodes (which seems fantastic) but I keep getting an "import failed" error in the ComfyUI Manager, even when I set its config.ini file to weak security level. I'm also unable to log this error on your discord as the discord link has expired. Kindly help, I'd really like to try the griptape nodes !

**Comment by shhlife** [comment]
Hi @poldos - thanks so much for wanting to try them out! I'd love to help solve the installation issue.

How are you launching ComfyUI? Are you doing it from a terminal where you can see the output? If so, can you show me the section of the output where it's trying and failing to install the nodes?

**Comment by poldos** [comment]
Hi Jason,

Thanks for reverting so quickly. I have installed the Windows  portable version of ComfyUI on a standalone machine, launched with a batch file in the terminal indeed. Here is the error message displayed when it attempts to load the nodes:

Traceback (most recent call last):
  File "C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2012, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Griptape\__init__.py", line 65, in <module>
    from .nodes.config.gtUIStructureConfig import gtUIStructureConfig
  File "C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Griptape\nodes\config\gtUIStructureConfig.py", line 23, in <module>
    has_openai_key = settings.get_settings_key_or_use_env(default_env) is not None
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Griptape\py\griptape_settings.py", line 103, in get_settings_key_or_use_env
    raise ValueError(f"Environment variable {env} is not set")
ValueError: Environment variable OPENAI_API_KEY is not set

Cannot import C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Griptape module for custom nodes: Environment variable OPENAI_API_KEY is not set


I hope this helps you identify where the problem comes from. I understand there is a problem with an environment variable but I don't know how/where to fix this.

Cheers,

Poldo

**Comment by poldos** [comment]
Hi Jason,

Being a little bit more awake this morning, I decided to ignore the Nov 1st changelog and to create a .env file with my open_ai key in it manually and... it worked !

I conclude that it is still necessary to create this file manually, unlike what is said in the changelog. Matter resolved. I should have thought of it before, sorry for the disturbance !

Cheers,

Poldo

**Comment by shhlife** [comment]
Hi @poldos - I've just pushed a new release that resolves this issue. Please try it out and re-open this if it still isn't working. :)

cheers!

**Comment by poldos** [comment]
Now that it works, I'm not to keen in uninstalling to see if it will work from scratch without .env file... Hope you don't mind.
I'm gonna get playin' with those nodes. If I find any bug or any idea to make them even better, I'll drop you a line.

Cheers & thanks again

Poldo

**Comment by shhlife** [comment]
Heya @poldos I totally understand. :)

When you do go ahead and update the nodes at some point in the future, please let me know if you run into any issues!

**Comment by poldos** [comment]
Sure, I will. Up to now, it’s all working like a breeze. 👍

Poldo
