### ISSUE TITLE
UI Request : Node Colors

### ISSUE THREAD

**Issue by nodegraphics** [griptape-ai/ComfyUI-Griptape#17]
First, thank you for the set of nodes! It is working great. I will be watching for your updates for sure. It opens up another world integrating Griptape.

`For my request, I would appreciate it if you could leave the node color as default (no color). When I change the theme to light, it becomes unreadable. I basically have to right-click and change the node color to default (no color).`

![Screenshot - 2024-06-11 19 35 26](https://github.com/griptape-ai/ComfyUI-Griptape/assets/10071439/c76cf247-d699-4612-8e60-d10b803f3463)

![Screenshot - 2024-06-11 19 23 34](https://github.com/griptape-ai/ComfyUI-Griptape/assets/10071439/113f0973-d938-4a19-94a9-8723bf11f0b6)

**Comment by shhlife** [comment]
Ah, that's a great comment - thank you so much! I'm glad you're enjoying the nodes. I'll see if I can get dark/light mode working properly - and if not, I'll just disable the colors. :) Will get right on it!

cheers,
Jason

**Comment by nodegraphics** [comment]
@shhlife Thank you Jason. 🙏

**Comment by shhlife** [comment]
My pleasure @nodegraphics , I just merged the fix - please let me know if this continues to be an issue for you! :)
