### ISSUE TITLE
Ollama Tool not working for Qwen models

### ISSUE THREAD

**Issue by RYG81** [griptape-ai/ComfyUI-Griptape#183]
hi,
I have been trying to figure out a multi agent workflow with Griptape and ollama. i have tried various Qwen models and found that for some reason the tool is not working. Please help with this.

![image](https://github.com/user-attachments/assets/5af77189-d210-4597-b036-c06fb7c5ace9)

![image](https://github.com/user-attachments/assets/0b7f867e-8b06-4147-a6a6-b7dbff36c5f2)

![image](https://github.com/user-attachments/assets/33bef04f-4dcf-47ce-802c-a94ede38ad24)

Rahul

**Comment by shhlife** [comment]
Okay, I was able to get qwen2.5:7b working with a simple tool - will try now with multiple tools

![image](https://github.com/user-attachments/assets/dfeaf7b8-a31e-440a-8867-3c40d9eeb9be)

**Comment by shhlife** [comment]
here's one where I converted a couple of agents to tools and then provided them to qwen2.5 as well, and that seemed to work..

can you try with the latest update to the Griptape ComfyUI nodes?

![image](https://github.com/user-attachments/assets/5f023422-eed6-4323-a78b-7d660df622b5)

**Comment by shhlife** [comment]
Will close for now - please re-open if it's still not working for you.
