### ISSUE TITLE
Installing issue

### ISSUE THREAD

**Issue by gontz** [griptape-ai/ComfyUI-Griptape#185]
When trying to install the plugin , this error comes up. 
ImportError: cannot import name 'AudioTranscriptionEngine' from 'griptape.engines'

Please advise

**Comment by shhlife** [comment]
I'll take a look, thank you!

were you installing through the ComfyUI manager, or by using the pip commands?

**Comment by griptape-studio** [comment]
Okay, poetry shouldn't have been required - but I'm glad you got that resolved! We did just update the framework to 1.0 which removed the need for the engines, but the Griptape ComfyUI nodes should be locked on the previous version - I'll take a look this morning and see if I can get it updated to 1.0 and solve the issue.

cheers!

**Comment by shhlife** [comment]
Hi @gontz - I've just released an update to the Griptape ComfyUI nodes - can you try uninstalling and re-installing again?

thank you!

**Comment by RamonGuthrie** [comment]
> Through Manager. Before that, there was another error too , the missing of the black forest module. And that I solved through pip install poetry first and pip install git+https://github.com/griptape-ai/griptape-black-forest.git after.

Yes I'm getting the same issue 

_```
Traceback (most recent call last):
  File "D:\Stable_Diffusion\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2035, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Stable_Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Griptape\__init__.py", line 122, in <module>
    from .nodes.drivers.gtUIBlackForestImageGenerationDriver import (
  File "D:\Stable_Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Griptape\nodes\drivers\gtUIBlackForestImageGenerationDriver.py", line 1, in <module>
    from griptape.black_forest.drivers.black_forest_image_generation_driver import (
ModuleNotFoundError: No module named 'griptape.black_forest'

Cannot import D:\Stable_Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Griptape module for custom nodes: No module named 'griptape.black_forest'
```_

**Comment by shhlife** [comment]
Okay, interesting - for some reason it's not finding that extension.

if you just do:
pip install git+https://github.com/griptape-ai/griptape-black-forest.git

what messags do you get?

**Comment by gontz** [comment]
I uninstalled and reinstalled and it **works**. No more error about audio engine.

**Comment by shhlife** [comment]
YES!

that's great, thank you :)

definitely let me know if you run into any more issues!
