### ISSUE TITLE
Tools : File Manager Question

### ISSUE THREAD

**Issue by nodegraphics** [griptape-ai/ComfyUI-Griptape#19]
Hi,
I have couple of questions about File Manager;

1) When i try to load it i believe im not formatting it right. and im getting this error. I used 
![Screenshot - 2024-06-12 13 19 23](https://github.com/griptape-ai/ComfyUI-Griptape/assets/10071439/52aa1e96-a0c8-49f3-96d0-ebce9e5f52dc)

2) Can i use this node to go through a directory with various formats or does it only support .txt files ?

////

as an extra general question;

What does off_prompt switch do ?

![Screenshot - 2024-06-12 13 25 57](https://github.com/griptape-ai/ComfyUI-Griptape/assets/10071439/6a8a7940-3ba4-4282-b8f3-2d368814be18)

Thank you

_Emrah

**Comment by shhlife** [comment]
Hi!

Ah, thanks for the issue on the file manager. I believe there was a change in the Griptape Framework recently that removed the requirement for the workdir.. I'll fix that & push a new release shortly.

"Off Prompt" is a unique Griptape feature that allows it to keep information from going back to the LLM until it's necessary. It's especially helpful when getting large amounts of data - like scraping web pages, etc. In many cases you can leave it False, and that's fine.

Here's some upcoming documentation on the framework for it: https://docs.griptape.ai/latest/griptape-framework/structures/task-memory/
