### ISSUE TITLE
Ollama agent config no longer working after an update

### ISSUE THREAD

**Issue by serget2** [griptape-ai/ComfyUI-Griptape#192]
I updated (yeah I know) and after a serious problem with the Unet loader andother problem creeped up I now only notice, the Ollama agent config is outlined in red as if it can no longer find the Ollama running on my system. Different port? Just like the Unet loader it says "undefined" in the embedding model driver widget, and maybe just like with the Unet loader it is a different folder that is adressed now (Instead of Unet folder which is deprecated it is now the Diffusion_models folder), so maybe comfyUI changed that?
The Gemini model does not have that problem and works just fine

**Comment by serget2** [comment]
hold the phone, now it seems to work again, strange. sorry for disturbing you

**Comment by serget2** [comment]
Pebkac or ID-10-T problem

**Comment by shhlife** [comment]
lol - no worries at all, glad it's working! :)
