### ISSUE TITLE
Depreciate DuckDuckGoWebSearch Driver

### ISSUE THREAD

**Issue by shhlife** [griptape-ai/ComfyUI-Griptape#193]
Unfortunately the DuckDuckGoWebSearchDriver relies on `duckduckgo_search` which is no longer maintained and has been archived. We will need to Depreciate it, unless we can find a replacement.

**Comment by deedy5** [comment]
It's already fine, update to the latest version
https://pypi.org/project/duckduckgo-search/

**Comment by collindutter** [comment]
No longer needed, https://github.com/griptape-ai/griptape/pull/1474
