### ISSUE TITLE
tts node stoped working 

### ISSUE THREAD

**Issue by Bolsdip** [griptape-ai/ComfyUI-Griptape#203]
- [x] I have read and agree to the [contributing guidelines](https://github.com/griptape-ai/griptape#contributing).

**Describe the bug**
Text-to-Speech Node isn't working anymore, it was working a few days ago.

Elevenlabs as driver error:
NameError: name 'ElevenLabs' is not defined  

OpenAI as driver error:
Error opening <_io.BytesIO object at 0x0000024D779E49A0>: File contains data in an unknown format.

**To Reproduce**
Use the example template. 

**Expected behavior**
Preview audio.

**Desktop (please complete the following information):**

- OS: Windows
- Version 10

**Additional context**
Using the latest version of ComfyUI, all updated.

**Comment by shhlife** [comment]
Hello @Bolsdip - can you share a screenshot of your Workflow? Thank you!

**Comment by Bolsdip** [comment]
![image](https://github.com/user-attachments/assets/022cb8be-4c0e-454e-8572-7a39e055c71e)

**Comment by shhlife** [comment]
This looks like it's using the OpenAI text to speech instead of Eleven Labs.. do you have an OPENAI_API_KEY set in the griptape settings?

**Comment by shhlife** [comment]
here's the eleven labs node:
![image](https://github.com/user-attachments/assets/36bc704c-5209-44ad-9b9a-3ba5316f1aba)

**Comment by Bolsdip** [comment]
Yes I have both of them setup in the settings. 
Also, my workflow looked like that too with ElevenLabs as driver.
Did you do that just now?
It was working yesterday

**Comment by shhlife** [comment]
Yes I tried it just before posting. Can you check your api key?

**Comment by Bolsdip** [comment]
All setup ok and multiple credits availble. 

I noticed if I use ElevenLabs as a driver, it uses up credits even though there's an error (NameError: name 'ElevenLabs' is not defined). 

If I use OpenAI as driver it doesn't use up any credits just this error: "Error opening <_io.BytesIO object at 0x0000024D779E49A0>: File contains data in an unknown format.".

Also, I've tried reinstalling. Same errors.

**Comment by Bolsdip** [comment]
Redownloaded ComfyUI and installed just Griptape, now it works.
Probably it was due to installing the other Text-to-speech nodes available, after I tested Griptape. Even though I've uninstalled them. I should have used different environments for each one.

Thanks for the help!

**Comment by shhlife** [comment]
awesome, glad to hear it's working! :)
