### ISSUE TITLE
open ai  Is it official only? I need to use the OPEN AI API key for other platforms

### ISSUE THREAD

**Issue by laitianwen** [griptape-ai/ComfyUI-Griptape#21]

**Comment by kyleroche** [comment]
Hi, can you explain your question a bit more please?

**Comment by laitianwen** [comment]
[report an error](http://www.youdao.com/w/report%20an%20error/#keyfrom=E2Ctranslation)：Converting to base64
Base64 Conversion Successful
HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 401 Unauthorized"
<RetryCallState 2879511523664: attempt #1; slept for 0.0; last result: failed (AuthenticationError Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-MFjJ3***************************************8665. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}})>

my url An interface to a third-party platform  :"OPENAI_API_BASE_URL": "https://cfcus02.opapi.win/v1",

**Comment by shhlife** [comment]
Hi, you should be able to use the same api key as you use for other applications - it's saved in .env as OPENAI_API_KEY?

**Comment by shhlife** [comment]
Oh - I think I understand - you are using OpenAI through another platform? What's the other platform?

**Comment by laitianwen** [comment]
the other platform:&nbsp;&nbsp;https://www.ohmygpt.com/
&nbsp;


江离
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jason ***@***.***&gt;; 
发送时间: 2024年6月16日(星期天) 下午3:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [griptape-ai/ComfyUI-Griptape] open ai  Is it official only? I need to use the OPEN AI API key for other platforms (Issue #21)














 
Oh - I think I understand - you are using OpenAI through another platform? What's the other platform?

**Comment by shhlife** [comment]
Okay - thank you. At the moment I don't think we have a config that would work for this one, but I can look into it. Thank you for bringing it to our attention!

**Comment by laitianwen** [comment]
Thanks and look forward to you joining it&nbsp;


江离
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jason ***@***.***&gt;; 
发送时间: 2024年6月16日(星期天) 下午3:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [griptape-ai/ComfyUI-Griptape] open ai  Is it official only? I need to use the OPEN AI API key for other platforms (Issue #21)














 
Okay - thank you. At the moment I don't think we have a config that would work for this one, but I can look into it. Thank you for bringing it to our attention!

**Comment by freshlesh3** [comment]
Can you 

> Okay - thank you. At the moment I don't think we have a config that would work for this one, but I can look into it. Thank you for bringing it to our attention!

Can you explain how to setup the use of local LLMs? The documentation just tells you how to install Ollama without directions on how to connect the two.

**Comment by shhlife** [comment]
Sure thing!

There is a video coming out pretty soon that demonstrates it, but until then here's the rough process:

1. Install Ollama following their install instructions on https://ollama.com
2. Add your model by typing something like: `ollama run llama3`. This will download the model the first time you run it.
3. In comfyUI, choose RMB -> Griptape -> Agent Helpers -> Ollama Config. This will add the ollama configuration for agents.
4. Choose the model 
5. Create a new agent by going RMB -> Griptape -> Agent -> create Agent
6. Connect the config to the agent.config input

There you go!

The video goes into some of the unique challenges when using these lower-end models, especially when using Tools. But for chatting it should work fine.

Please let me know if this works for you!
-Jason

**Comment by shhlife** [comment]
The video is out now on youtube - can you give it a try?

https://www.youtube.com/watch?v=jIq_TL5xmX0&t=384s

**Comment by shhlife** [comment]
The latest release has a new node the `Griptape Config: OpenAI Compatible node` which allows you to use any API that is compatible with OpenAI. 

So you can use OhMyGPT with it. :) Enjoy!

![image](https://github.com/user-attachments/assets/84d8d235-4b09-4b6e-a76a-7b1e0f8cb644)

**Comment by laitianwen** [comment]
Wow~ Finally, it's here, that's so cool！






------------------ Original ------------------
From: Jason Schleifer ***@***.***&gt;
Date: Sat,Jul 13,2024 8:50 AM
To: griptape-ai/ComfyUI-Griptape ***@***.***&gt;
Cc: laitianwen ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [griptape-ai/ComfyUI-Griptape] open ai  Is it official only? Ineed to use the OPEN AI API key for other platforms (Issue #21)





 
The latest release has a new node the Griptape Config: OpenAI Compatible node which allows you to use any API that is compatible with OpenAI.
 
So you can use OhMyGPT with it. :) Enjoy!
 
image.png (view on web)

**Comment by shhlife** [comment]
Definitely check it out and let us know what you think!

**Comment by laitianwen** [comment]
Great, this node supports Claude 3.5 as well, right? 😍

**Comment by shhlife** [comment]
if OhMyGpt does, then it should - please let me know if it doesn't! :)

I did just push a quick fix.. fixed a spelling error & also added a prompt config for huggingface.

![image](https://github.com/user-attachments/assets/0f36ef9b-82ec-4ea3-aaa6-dbc72c4e6a97)

**Comment by laitianwen** [comment]
It worked, it works, it's perfect, thank you for your service
&nbsp;


江离
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jason ***@***.***&gt;; 
发送时间: 2024年7月13日(星期六) 上午8:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [griptape-ai/ComfyUI-Griptape] open ai  Is it official only? I need to use the OPEN AI API key for other platforms (Issue #21)














 
The latest release has a new node the Griptape Config: OpenAI Compatible node which allows you to use any API that is compatible with OpenAI.
 
So you can use OhMyGPT with it. :) Enjoy!
 
image.png (view on web)
