### ISSUE TITLE
Can not connect to APIs

### ISSUE THREAD

**Issue by freshlesh3** [griptape-ai/ComfyUI-Griptape#36]
I have installed the correct API key and getting this error. I have used the Anthropic and OpenAI keys. I created the .env file with the API key string and restarted comfyui:

Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-2bOuG***************************************II7o. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}

**Note that the API key that is shown is not the one I placed in the .env for some reason, it shows a previous version in the error message. 

I am using windows 11, with Comfyui portable build

**Comment by shhlife** [comment]
Good morning - are you still seeing the issue?

Where is your `.env` file located? Is it in the main ComfyUI folder, or in the ComfyUI-Griptape folder?

**Comment by shhlife** [comment]
@freshlesh3 just checking in to see if you've had a chance to try again?

**Comment by freshlesh3** [comment]
> Good morning - are you still seeing the issue?
> 
> Where is your `.env` file located? Is it in the main ComfyUI folder, or in the ComfyUI-Griptape folder?

Hey thanks for the response.  I think I had a 

> @freshlesh3 just checking in to see if you've had a chance to try again?

Hey thanks for the response my .env file is in my \ComfyUI\.env folder.

**Comment by freshlesh3** [comment]
> > Good morning - are you still seeing the issue?
> > Where is your `.env` file located? Is it in the main ComfyUI folder, or in the ComfyUI-Griptape folder?
> 
> Hey thanks for the response. I think I had a
> 
> > @freshlesh3 just checking in to see if you've had a chance to try again?
> 
> Hey thanks for the response my .env file is in my \ComfyUI.env folder and still not working.



> > Good morning - are you still seeing the issue?
> > Where is your `.env` file located? Is it in the main ComfyUI folder, or in the ComfyUI-Griptape folder?
> 
> Hey thanks for the response. I think I had a
> 
> > @freshlesh3 just checking in to see if you've had a chance to try again?
> 
> Hey thanks for the response my .env file is in my \ComfyUI.env folder and still not working.

Actually I just tried it and updated the custom nodes and its working now.  Both Ollama and the Claude Sonnet models are working great.  Thanks for the follow up and the assist @shhlife

**Comment by freshlesh3** [comment]
Correction.  I get this error when I run a griptape run: Image description now.
Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-2bOuG***************************************II7o. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}

**Comment by shhlife** [comment]
Looks like it was working for a second, and now it isn't! D'oh! :)

can you show me an image of your graph so I can help debug?

cheers!
-Jason

**Comment by freshlesh3** [comment]
> Looks like it was working for a second, and now it isn't! D'oh! :)
> 
> can you show me an image of your graph so I can help debug?
> 
> Cheers! -jason

Here is my workflow.
![Screenshot 2024-06-28 182310](https://github.com/griptape-ai/ComfyUI-Griptape/assets/4007491/cc97cdf3-2721-40af-9367-a6d7878865e4)

**Comment by shhlife** [comment]
Okay, yeah it looks like it's not getting the OPENAI api key.. and it's set in your `.env` file on disk?

**Comment by shhlife** [comment]
If you're looking to use Claude, you'll need to create a config & then connect that to an agent, and connect the agent to the Run Image Description.. this is because the default agent uses OpenAI

![image](https://github.com/griptape-ai/ComfyUI-Griptape/assets/5397345/d7bff353-9ff1-407a-8855-66d5401e69bc)

**Comment by freshlesh3** [comment]
> If you're looking to use Claude, you'll need to create a config &amp; then connect that to an agent, and connect the agent to the Run Image Description.. this is because the default agent uses OpenAI
> 
> [![image](https://private-user-images.githubusercontent.com/5397345/344347175-d7bff353-9ff1-407a-8855-66d5401e69bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2MTk5NTYsIm5iZiI6MTcxOTYxOTY1NiwicGF0aCI6Ii81Mzk3MzQ1LzM0NDM0NzE3NS1kN2JmZjM1My05ZmYxLTQwN2EtODg1NS02NmQ1NDAxZTY5YmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjlUMDAwNzM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmM1NmI5Y2ZlNGM0YWMyMWU2Y2YxNTk1MGMxNmNjMzQ0ZjE3MWQ1NGNjODAwNjNmNWM1MzljYTQ0NDU2N2Q2MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.IUh-UjpFTT-TNC4jW0AFZCb3eepr9tezNUL47mgyNrs)](https://private-user-images.githubusercontent.com/5397345/344347175-d7bff353-9ff1-407a-8855-66d5401e69bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2MTk5NTYsIm5iZiI6MTcxOTYxOTY1NiwicGF0aCI6Ii81Mzk3MzQ1LzM0NDM0NzE3NS1kN2JmZjM1My05ZmYxLTQwN2EtODg1NS02NmQ1NDAxZTY5YmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjlUMDAwNzM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmM1NmI5Y2ZlNGM0YWMyMWU2Y2YxNTk1MGMxNmNjMzQ0ZjE3MWQ1NGNjODAwNjNmNWM1MzljYTQ0NDU2N2Q2MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.IUh-UjpFTT-TNC4jW0AFZCb3eepr9tezNUL47mgyNrs)

The Claude API is working, but as I am testing all of the pipelines I have issues running LM Studio, and Ollama

**Comment by shhlife** [comment]
Ah, okay - I've just pushed a new update that allows you to set the url & port - can you give it a try?

![image](https://github.com/griptape-ai/ComfyUI-Griptape/assets/5397345/0aaaa1d5-36a8-468a-abd6-c12343663aa3)

**Comment by shhlife** [comment]
LM Studio should be working. Closing for now, but please re-open if you continue to have issues. :)

**Comment by freshlesh3** [comment]
> LM Studio should be working. Closing for now, but please re-open if you continue to have issues. :)

Hey thanks for your reply. I still am not able to use the Ollama or OpenAI nodes. I get a: 
'got prompt
Prompt executed in 0.27 seconds'

response in terminal, I am running Ollama and when using the Griptape Agent Config: Ollama node I get a blank 'prompt model' drop down list and unable to select a model.

![image](https://github.com/user-attachments/assets/ddad48ff-b1a6-4c7a-a943-29a0739e25a2)
