### ISSUE TITLE
Nodes naming in canvas

### ISSUE THREAD

**Issue by nodegraphics** [griptape-ai/ComfyUI-Griptape#37]
When I use the sidebar, I believe the Griptape Nodes uses class names when it's dragged and dropped onto the canvas.

![griptape_01](https://github.com/griptape-ai/ComfyUI-Griptape/assets/10071439/15c247f5-b4f9-4676-8779-29d5c73d8ece)

**Comment by shhlife** [comment]
Woah - what is this sidebar? I've never seen that :)

**Comment by nodegraphics** [comment]
very useful sidebar from [Nuked](https://github.com/Nuked88/ComfyUI-N-Sidebar)

**Comment by shhlife** [comment]
Fantastic - I’ll check it out tomorrow and see what I can do to fix it :)
thanks!

**Comment by shhlife** [comment]
Ahh - I checked out the addon this morning. It's super awesome - and something I've been wanting for a while!

Unfortunately it highlighted a problem I need to look into.

When I'm initializing my nodes in the `__init__.py` file, I'm doing something like this:

```
NODE_CLASS_MAPPINGS = {
    "gtUIInputNode": gtUIInputStringNode,
    "gtUIFetchImage": gtUIFetchImage,
}
```
```
NODE_DISPLAY_NAME_MAPPINGS = {
    "gtUIInputNode": "Griptape Create: Text",
    "gtUICLIPTextEncode": "Griptape Create: CLIP Text Encode",
```

I thought that the `NODE_DISPLAY_NAME_MAPPINGS` would name the nodes correctly.. but it looks like what I actually need to do is name it in the `NODE_CLASS_MAPPINGS` variable.

If I just change it to what I want the name to be, then all the existing nodes will be broken.

I need to figure out how to fix the naming properly - or ask the dev if they can update the node names to use the `NODE_DISPLAY_NAME_MAPPINGS`.. or figure out if there's a way to convert nodes.

**Comment by nodegraphics** [comment]
ouu got it. yeahh its better to keep it same for now. I dont think its a big deal. i just noticed it while working and wanted to open a topic. Otherwise all is working great.
