### ISSUE TITLE
can't use combine text to set a lora name string widget.

### ISSUE THREAD

**Issue by spiraloid** [griptape-ai/ComfyUI-Griptape#44]
![image](https://github.com/griptape-ai/ComfyUI-Griptape/assets/36362743/b3c9d22b-4d11-46c0-bf89-4850575bfe26)

**Comment by shhlife** [comment]
Thanks @spiraloid - taking a look!

It looks like the issue may be that the input type for `lora_name` is an item from a list.. 

Here's how it's defined in the class:
```
    @classmethod
    def INPUT_TYPES(s):
        return {"required": { "model": ("MODEL",),
                              "clip": ("CLIP", ),
                              "lora_name": (folder_paths.get_filename_list("loras"), ),
                              "strength_model": ("FLOAT", {"default": 1.0, "min": -100.0, "max": 100.0, "step": 0.01}),
                              "strength_clip": ("FLOAT", {"default": 1.0, "min": -100.0, "max": 100.0, "step": 0.01}),
                              }}
```
I'll have to dig around and see if I can figure out what type of value it takes. 

Workin on it! :)

**Comment by shhlife** [comment]
Okay, I've just pushed a new node that will convert a string to a combo input type..

![image](https://github.com/griptape-ai/ComfyUI-Griptape/assets/5397345/cfac1a56-e98a-4bed-95d8-ebe343110963)

Can you pull the latest and give it a try?

Thanks! :)

**Comment by spiraloid** [comment]
awwww yeah
