### ISSUE TITLE
Can't identify my OPENAI_API_KEY in .env file

### ISSUE THREAD

**Issue by aldkfjwe** [griptape-ai/ComfyUI-Griptape#52]
I'm running the sample code from Github page and found out it used my old api key that resulted in this error. 

<img width="722" alt="image" src="https://github.com/griptape-ai/griptape/assets/173952850/b0b4cadc-5487-41b6-9ad7-00203420eba8">

I then added my newer API key to the .env file in root file of the project: OPENAI_API_KEY = 'my new version of the key'. However, after I added this line, the code still used older version, instead of the key provided in environment file. Is there any file should I create to configure the API key?

**Comment by tolseee** [comment]
> Hi @tolseee - in your .env, do you have spaces between OPENAI_API_KEY and the = sign and your key?
> 
> Does it look like this:
> 
> ```
> OPENAI_API_KEY=yourapikey
> ```
> 
> or
> 
> ```
> OPENAI_API_KEY = yourapikey
> ```

OPENAI_API_KEY=sk-proj-WKF[...]

**Comment by shhlife** [comment]
Hmm.. okay.. this is interesting. are you on windows or mac?

One thing to try.. in the shell where you're running comfyUI, try and run python by just executing:

`python`

This should put you in a shell that looks something like:

```
Python 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

Then run:
```
import os
os.getenv("OPENAI_API_KEY")
```

This should show the default API key set for your environment. If it's the old one, then do:

```
from dotenv import load_dotenv
load_dotenv()
```

This will force python to get the keys from your `.env` file

then again do:
```
os.getenv("OPENAI_API_KEY")
```

Are they the same?

The other question.. is your `.env` located in the same directory you're running comfyUI from?

**Comment by tolseee** [comment]
> os.getenv("OPENAI_API_KEY")

This is what I get

PS C:\SD\[...]\ComfyUI_windows_portable\ComfyUI> python
Python 3.10.14 (main, Mar 20 2024, 14:08:13) [MSC v.1939 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> import os
>>> os.getenv("OPENAI_API_KEY")
'sk-proj-WKF[...]YvwcYI'
>>> from dotenv import load_dotenv
>>> load_dotenv()
True
>>> os.getenv("OPENAI_API_KEY")
'sk-proj-WKF[...]YvwcYI'
>>>


> The other question.. is your .env located in the same directory you're running comfyUI from?

Yes


Honestly I have no idea where the AuthenticationError: Error code: 401 - {'error': {'message': 'Incorrect API key
                             provided: sk-proj-********************************************jP2D. API is coming from

**Comment by shhlife** [comment]
Yeah, it's very strange!

Okay, here's another thing to try..

in your `custom_nodes/ComfyUI-Griptape/` folder there should be a file called `griptape_config.json`.

If you open that file, you should see something that looks like:

```
{
    "env": {
        "OPENAI_API_KEY": "sk-****",
    }
}
```

is that the right api key?

If not, try deleting the griptape_config.json file and restarting comfyui

-Jason

**Comment by tolseee** [comment]
> Yeah, it's very strange!
> 
> Okay, here's another thing to try..
> 
> in your `custom_nodes/ComfyUI-Griptape/` folder there should be a file called `griptape_config.json`.
> 
> If you open that file, you should see something that looks like:
> 
> ```
> {
>     "env": {
>         "OPENAI_API_KEY": "sk-****",
>     }
> }
> ```
> 
> is that the right api key?
> 
> If not, try deleting the griptape_config.json file and restarting comfyui
> 
> -Jason

You got it. 
It was pointing at the wrong API, deleted and now it's pointing to the right one. 

Now I'm facing a new issue but I'll open a new thread to avoiding off topic posts :)

**Comment by shhlife** [comment]
my pleasure!
