### ISSUE TITLE
Update Read me with new requirements

### ISSUE THREAD

**Issue by william-price01** [griptape-ai/ComfyUI-Griptape#92]
**Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": [*https://visualstudio.microsoft.com/visual-cpp-build-tools/*](url)

**Comment by shhlife** [comment]
Hey @william-price01 - sorry, just getting back to this. Can you confirm where you needed to install the Microsoft Visual C++ build tools?

**Comment by shhlife** [comment]
We aren't sure if this is a one-time thing or is something everyone would hit - if we get more instances of it, we'll re-address!

thanks :)
